# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

FROM python:2.7-alpine

RUN apk --update --no-cache add \
  gcc \
  linux-headers \
  musl-dev

COPY requirements /requirements
RUN pip install --no-cache --require-hashes -r /requirements/production.txt && \
    pip install --no-cache --require-hashes -r /requirements/development.txt

COPY . /app
WORKDIR /app

# We install outside of the app directory to create the .egg-info in a
# location that will not be mounted over. This means /app/src needs to be
# added to PYTHONPATH though.
RUN cd / && python /app/setup.py develop
ENV PYTHONPATH=/app/src/
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["neotoma"]
CMD ["dev-server"]
